# V1 - Config with up to 600 filtered points. 
# V2 - Config with up to 750 filtered points.
# V3 - Config with up to 3500 filtered points.
# V3 - Config with up to 3800 filtered points.
# V4 - Config with up to 4000 filtered points.

# FRONT END.
scan_matcher:
  ros__parameters:
    global_frame_id: "map"
    robot_frame_id: "base_link"
    registration_method: "NDT"  # Normal Distributions Transform (NDT).
    ndt_resolution: 1.0  # Size of a voxel for NDT  
    ndt_num_threads: 0  # As many as you can.
    gicp_corr_dist_threshold: 0.1  # Does this affect NDT?
    trans_for_mapupdate: 0.8  # I think the map is updated only if we move by this much.
    vg_size_for_input: 0.03  # Voxel dimension for input PCD.
    vg_size_for_map: 0.03   # Voxel dimension for map.
    use_min_max_filter: true  # ???
    scan_min_range: 0.3
    scan_max_range: 15.0
    scan_period: 0.2  # Useful in case one uses IMU?
    map_publish_period: 1.0 
    num_targeted_cloud: 150
    set_initial_pose: true
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_qx: 0.0
    initial_pose_qy: 0.0
    initial_pose_qz: 0.0
    initial_pose_qw: 1.0
    use_imu: false
    use_odom: false
    debug_flag: true

# BACK END.
graph_based_slam:
    ros__parameters:
      registration_method: "NDT"
      ndt_resolution: 1.0  
      ndt_num_threads: 0  # As many as possible.
      voxel_leaf_size: 0.05
      loop_detection_period: 3000
      threshold_loop_closure_score: 0.7
      distance_loop_closure: 100.0
      range_of_searching_loop_closure: 20.0
      search_submap_num: 2
      num_adjacent_pose_cnstraints: 5
      use_save_map_in_loop: true
      debug_flag: true

